spring.application.name=SFU PA Project
# Spring Security settings to allow H2 console access
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:file:./data/h2database
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
#CHANGE THIS BEFORE DEPLOYMENT PLEASE!!!!!

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Disable security for H2 console
spring.h2.console.settings.web-allow-others=true
# CHANGE THIS BEFORE DEPLOYMENT TOO - WILL HAVE TO MODIFY THESE
